# Generated by Django 5.2.5 on 2025-11-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
