# Generated by Django 5.2.5 on 2025-11-28 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_enrolledcourse_ended_at'),
        ('lms', '0001_initial'),
        ('payment', '0003_transaction_courses_earning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', help_text='Enrollment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrolledcourse',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='Enrollment expiration date (auto-set to 30 days from start)', null=True),
        ),
        migrations.AddIndex(
            model_name='enrolledcourse',
            index=models.Index(fields=['user', 'course'], name='course_enro_user_id_b1fe3e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolledcourse',
            index=models.Index(fields=['user', 'status'], name='course_enro_user_id_9732d4_idx'),
        ),
    ]
