# Generated by Django 5.2.5 on 2025-12-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_enrolledcourse_status_alter_enrolledcourse_ended_at_and_more'),
        ('payment', '0003_transaction_courses_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.cartorderitem'),
        ),
    ]
