# Generated by Django 5.2.5 on 2025-12-06 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_enrolledcourse_order_item'),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.student'),
        ),
    ]
