# Generated by Django 5.2.5 on 2025-12-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_enrolledcourse_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_answer_message',
            name='qa_id',
        ),
        migrations.AlterField(
            model_name='course',
            name='platform_status',
            field=models.CharField(blank=True, choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_url_or_text',
            field=models.TextField(help_text='File URL or long text content.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], default=1),
        ),
    ]
