# Generated by Django 5.2.5 on 2025-12-27 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_question_answer_message_qa_id_and_more'),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('meeting_id', models.CharField(blank=True, help_text='Zoom Meeting ID', max_length=50, null=True)),
                ('meeting_password', models.CharField(blank=True, max_length=50, null=True)),
                ('join_url', models.URLField(blank=True, help_text='Link for students', max_length=1000, null=True)),
                ('start_url', models.URLField(blank=True, help_text='Link for teacher (host)', max_length=1000, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('attendance_synced', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='LiveAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(blank=True, null=True)),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='absent', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_attendance', to='lms.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='course.livesession')),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
    ]
