# Generated by Django 5.2.5 on 2025-12-27 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_livesession_liveattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
        migrations.AddField(
            model_name='assignment',
            name='lesson',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='course.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('time_limit', models.IntegerField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=1)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='course.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('points', models.IntegerField(default=1)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(blank=True, default='', max_length=255)),
                ('explanation', models.TextField(blank=True, default='')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course.quiz')),
            ],
        ),
    ]
