# Generated by Django 5.2.5 on 2025-12-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_recreate_completedlesson_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='lesson-documents/'),
        ),
    ]
