# Generated by Django 5.2.5 on 2025-12-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_lesson_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_url_or_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
