# Generated by Django 5.2.5 on 2026-01-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_quizattempt_quizattemptanswer_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the quiz closes', null=True),
        ),
    ]
