# Generated by Django 5.2.5 on 2026-01-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_quiz_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz-questions/'),
        ),
    ]
