# Generated by Django 5.2.5 on 2026-01-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='plagiarism_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
