# Generated by Django 5.2.5 on 2026-01-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_assignmentsubmission_plagiarism_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='plagiarism_report',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
