# Generated by Django 5.2.5 on 2026-01-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_assignmentsubmission_plagiarism_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Text content extracted from the file', null=True),
        ),
    ]
