# Generated by Django 5.2.5 on 2025-11-23 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=10)),
                ('type', models.CharField(choices=[('general', 'General'), ('course', 'Course'), ('assignment', 'Assignment'), ('urgent', 'Urgent')], default='general', max_length=20)),
                ('visibility', models.CharField(choices=[('everyone', 'Everyone'), ('students', 'Students Only'), ('teachers', 'Teachers Only')], default='everyone', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Date and time when this announcement will be automatically deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
