# Generated by Django 5.2.5 on 2025-11-11 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('instructor', 'Instructor'), ('receptionist', 'Receptionist')], default='student', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_temporary_password', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'lms_user',
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_receptionist', models.BooleanField(default=True)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email_Address', models.EmailField(max_length=254, unique=True)),
                ('Phone_Number', models.CharField(blank=True, default='', max_length=20)),
                ('Date_Joined', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'lms_receptionist',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_teacher', models.BooleanField(default=True)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email_Address', models.EmailField(max_length=254, unique=True)),
                ('Phone_Number', models.CharField(blank=True, default='', max_length=20)),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_Joined', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'lms_teacher',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='default-user.jpg', null=True, upload_to='user_folder')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lms_profile',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(blank=True, default='', max_length=100)),
                ('section', models.CharField(blank=True, default='', max_length=100)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_activity', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('image', models.FileField(blank=True, default='default.jpg', null=True, upload_to='student-file')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zipCode', models.CharField(blank=True, max_length=10, null=True)),
                ('guardianName', models.CharField(blank=True, max_length=200, null=True)),
                ('guardianPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergencyContact', models.CharField(blank=True, max_length=200, null=True)),
                ('emergencyPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('academicYear', models.CharField(choices=[('primary level', 'Primary Level'), ('ordinary level', 'Ordinary Level'), ('advanced level', 'Advanced Level')], default='primary level', max_length=50)),
                ('School', models.CharField(blank=True, max_length=200, null=True)),
                ('Grade', models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12'), ('Grade 13', 'Grade 13')], default='Grade 1', max_length=100)),
                ('registrationFees', models.BooleanField(default=False)),
                ('enrollmentDate', models.DateField(blank=True, null=True)),
                ('medicalInfo', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='lms.teacher')),
            ],
            options={
                'db_table': 'lms_student',
            },
        ),
    ]
