# Generated by Django 5.2.5 on 2025-11-11 16:52

import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Stripe, PayPal', max_length=100, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('publishable_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijk12345', length=20, max_length=20, prefix='', primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('oid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijk12345', length=20, max_length=20, prefix='', primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paid_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartOrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.cartorder')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('related_order_id', models.BigIntegerField(blank=True, help_text='ID of related CartOrder (matches database column)', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_type', models.CharField(choices=[('registration_fee', 'Registration Fee'), ('auto_renewal', 'Automated Renewal'), ('subscription_upgrade', 'Subscription Upgrade'), ('course_purchase', 'Course Purchase')], default='course_purchase', help_text='Type of transaction (e.g., Course Purchase, Subscription)', max_length=50)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=255, null=True, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe Customer ID', max_length=255, null=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='When payment is due', null=True)),
                ('paid_date', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('payment_method_used', models.CharField(blank=True, choices=[('card', 'Card'), ('bank', 'Bank Account'), ('physical', 'Physical'), ('bank_slip', 'Bank Slip'), ('other', 'Other'), ('stripe', 'Stripe')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, help_text='Payment reference/receipt number', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(blank=True, help_text='Gateway used for the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymentgateway')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_as_student', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_as_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
