# Generated by Django 5.2.5 on 2025-11-22 19:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('payment', '0002_remove_cart_course_id_cart_course_cart_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='course.course'),
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earning_type', models.CharField(choices=[('teacher', 'Teacher'), ('platform', 'Platform (Company)'), ('admin', 'Admin')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='course.course')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='payment.transaction')),
                ('user', models.ForeignKey(blank=True, help_text='The user receiving this money (Teacher or Admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
