# Generated by Django 5.2.5 on 2025-12-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_transaction_courses_earning'),
    ]

    operations = [
    ]
