# Generated by Django 5.2.5 on 2026-01-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted'), ('message', 'New Message'), ('group_invite', 'Group Invite'), ('group_message', 'Group Message'), ('group_member_added', 'Member Added to Group'), ('group_member_removed', 'Member Removed from Group'), ('plagiarism_alert', 'Plagiarism Alert'), ('misconduct_alert', 'Misconduct Alert'), ('assignment_due', 'Assignment Due')], max_length=50),
        ),
    ]
