"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
import environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f4m5n+km@7-2j^t(i%-!8q=%_)z&+0ken*#2kvxv#y7v&b$_kb'


DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'websocketking.com']

CHATBOT_API_KEY = os.environ.get("CHATBOT_API_KEY")

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "daphne",
    'django_celery_beat',
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    'rest_framework_simplejwt',
    "lms",
    "course",
    'notification.apps.NotificationConfig',
    "payment",
    "channels",
    "chatbot",
    "chatroom",
    
    
    

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # ✅ MOVED HERE - Must be before CommonMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


ROOT_URLCONF = 'backend.urls'

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "frontend", "src")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = "backend.asgi.application"


SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
            
        },
    },
}

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer"
#     }
# }

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    # Add any other domains where your frontend might be hosted
]
CORS_ALLOW_ALL_ORIGINS = True


STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY') 
STRIPE_PUBLIC_KEY = os.environ.get('STRIPE_PUBLIC_KEY')

AUTH_USER_MODEL = "lms.User"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

APPEND_SLASH = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication', 
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",  # ✅ Added for chat
    "PAGE_SIZE": 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),   # 24 hours
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30), # 30 days
}

# settings.py

REDIS_URL = 'redis://127.0.0.1:6379/0'

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_TIMEZONE = 'UTC'


# Email Configuration using SendGrid SMTP
# settings.py


# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_PORT = 2525
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'sendgrid API' # This must be exactly the string 'apikey'
EMAIL_HOST_PASSWORD = os.environ.get('SENDGRID_API_KEY') # Store your key in .env
DEFAULT_FROM_EMAIL = 'em7474.sipsara.lk' # Must match SendGrid verification  # Replace with your verified SendGrid sender email


WEBSOCKET_ACCEPT_ALL = False

# Chat-specific REST Framework settings
CHAT_PAGE_SIZE = 20

# Message retention (optional)
MESSAGE_RETENTION_DAYS = 30

# Maximum file size for chat attachments (10MB)
CHAT_MAX_FILE_SIZE = 10 * 1024 * 1024

# Allowed file types for chat
CHAT_ALLOWED_FILE_TYPES = ['image/jpeg', 'image/png', 'image/gif', 'application/pdf', 'text/plain']



GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET')


CELERY_BEAT_SCHEDULE = {
    # Run every 5 minutes to check for finished classes
    'mark-sessions-completed-every-5-min': {
        'task': 'course.tasks.mark_finished_sessions_completed',
        'schedule': 300.0,  # 300 seconds = 5 minutes
    },
    # Run every 5 minutes to check for upcoming classes
    'send-class-reminders-every-5-min': {
        'task': 'course.tasks.send_class_reminders',
        'schedule': 300.0,
    },
    'cleanup-expired-announcements-every-hour': {
        'task': 'notification.tasks.cleanup_expired_announcements', 
        'schedule': 3600.0,  # Run every 1 hour (3600 seconds)
    },
}